### ISSUE TITLE
WorldGuard not allowing exit tp after game finish.

### ISSUE THREAD

**Issue by elliot-labs** [Razz0991/Minigames#25]
I have set up worldguard to make a do not exit zone on one of my minigames (flag exit deny). when the game finishes it does not allow the player to be teleported out of the zone. I have to manually kill them. 

Could you fix this bug or implement your own border system similar to how regeneration works except that players cannot cross the boundary? 

Thank you!

**Comment by Schmoller** [comment]
Hey there, in the 1.7 builds on http://jenkins.addstar.com.au/job/Minigames/ there is a system called Regions. You can perform this action by using the following:
1. A region which surrounds the area you want to contain people within
2. A leave triggered executor on that region
3. The world->Barrier option in that executor.

This will prevent people from leaving during the game only

**Comment by elliot-labs** [comment]
thx I will take a look into it!
