### ISSUE TITLE
Spleef Setup

### ISSUE THREAD

**Issue by Grasty** [Razz0991/Minigames#28]
More of a Question/Feature Suggestion than an issue.

how are you intended to setup spleef? what flags would a typical spleef arena have set?

The reason I ask is because I dont see any "instabreak" flag for arenas so i have no way of allowing players to punch the floor and have it instantly despawn (as spleef should be). To remedy this, I gave all players an efficiency 5 hoe in the loadout. This worked great until players realized they can just smack eachother with the hoe and end the game faster.

So is there something I am missing that would allow instabreak on blocks? or is this a feature that can be added?

**Comment by Noket** [comment]
Do what we did.. Use world guard to create a region with pvp off build on.
Problem solved.

**Comment by Grasty** [comment]
Unfortunately, we use a different plugin to manage pvp, so the pvp flag doesnt do anything. Or at least last time i tried it, the pvp flag didnt work. I can try it again though.

**Comment by Noket** [comment]
If your pvp flag doesn't do anything, it might be an issue with your
configuration. Often times, if a flag is strictly defined (instead of left
blank) in your config.yml .. it'll override any settings that you
choose/enable ingame.

**Comment by skidbld** [comment]
Weakness. Edit the loadout and click on the potion. Add a weakness effect (it may be called decrease_damage) with a level of 100 to disable pvp entirely. Some blocks can instabreak with the right tools. Default spleef has snow blocks and a diamond shovel. If you want your players to be able to break blocks with your fists, do an easy to break block and give them fast_digging.

**Comment by Grasty** [comment]
Thanks for the info that will help!

Can you clarify what you mean by this, im not sure i understand what you mean.
"do an easy to break block and give them fast_digging."

Also, would the Weakness (or decrease damage) potion effect prevent them from taking damage to the lava under the platform?

**Comment by skidbld** [comment]
Do an easy block, like dirt for example. Basically any block that breaks fast with your fist is best, but not required. fast_digging is bukkit's word for haste. To register the potion you'd need to call it fast_digging.

The weakness would not, no. That is fire resistance. Weakness, as the name suggests, weakens the damage you deal to opponents. If that number goes higher or equal to the damage you deal, you can't attack at all.

**Comment by Grasty** [comment]
Thanks, fast_digging did the trick.
